/***********************************************************************
*
* Assignment 2, Part A - Signal Handling.
* ------------------------------------------------
* Team          : 10
* Date          : 6-August-2025
*
* Members:
* 1. Shoaib Mohammad      (Roll No: 002311001062)
* 2. Abu Darda Mallik     (Roll No: 302411001007)
* 3. Sagnik Kayal         (Roll No: 002311001046)
*
***********************************************************************************
*
* Assignment Details: Assignment 2, Part A - Signal Handling.
* This program demonstrates how to catch the SIGINT signal (generated by
* pressing Ctrl+C) using the 'signal' system call. It prevents the program
* from terminating and instead displays a custom message. The program runs
* in an infinite loop until terminated by a different signal, like SIGQUIT
* (Ctrl+\).
*
* Input Description:
* No command-line arguments are required. The program runs indefinitely and
* responds to keyboard signals sent from the terminal.
* - Press Ctrl+C to send the SIGINT signal.
* - Press Ctrl+\ to send the SIGQUIT signal to terminate the program.
*
* Output Description:
* - Initially, it prints instructions on how to interact with the program.
* - In a loop, it prints a status message "Program is still running...".
* - When Ctrl+C is pressed, it catches the SIGINT signal and prints the
* message "Ha Ha, Not Stopping" without terminating.
* - When Ctrl+\ is pressed, the operating system's default handler for
* SIGQUIT terminates the program.
*
* Compilation Command:
* gcc A2_10_2A.c -o A2_10_2A
*
* Execution Sequence:
* ./A2_10_2A
* (Then press Ctrl+C multiple times, and finally press Ctrl+\ to exit)
*
* Sample Input and Output:
* adminpc@adminpc:~$ gcc A2_10_2A.c -o A2_10_2A
* adminpc@adminpc:~$ ./A2_10_2A
* Program is running. Press Ctrl+C to test the SIGINT signal.
* Press Ctrl+\ to quit the program using SIGQUIT.
* Program is still running... Press Ctrl+C to test signal handling.
* ^C
* Ha Ha, Not Stopping
* Program is still running... Press Ctrl+C to test signal handling.
* Program is still running... Press Ctrl+C to test signal handling.
* ^C
* Ha Ha, Not Stopping
* Program is still running... Press Ctrl+C to test signal handling.
* ^\Quit (core dumped)
*
***********************************************************************/

#include <stdio.h>
#include <stdlib.h>
#include <signal.h>
#include <unistd.h> // For sleep()

void sigint_handler(int sig) {
    printf("\nHa Ha, Not Stopping\n");
}

int main() {
    // Register the signal handler for SIGINT
    if (signal(SIGINT, sigint_handler) == SIG_ERR) {
        perror("Error setting up signal handler for SIGINT");
        exit(EXIT_FAILURE); // Exit if the handler cannot be set
    }

    printf("Program is running. Press Ctrl+C to test the SIGINT signal.\n");
    printf("Press Ctrl+\\ to quit the program using SIGQUIT.\n");

    // Run an infinite loop to keep the program alive
    while (1) {
        printf("Program is still running... Press Ctrl+C to test signal handling.\n");
        sleep(1); // Pauses for 1 second to reduce CPU usage
    }

    return 0;
}